### ISSUE TITLE
Research question

### ISSUE THREAD

**Issue by cbrehmer97** [cbrehmer97/ERHS535_final_group5#1]
Position of daily doubles.

**Comment by cbrehmer97** [comment]
Data cleanup:
Evaluate if all daily doubles were picked in each episode

**Comment by hischkmj** [comment]
The data cleanup will need to take into account the x and y position. 
               Category 1       Category 2       Category 3       Category 4       Category 5        Category 6
100 
200               X
300 
400
500

We are going to have to make the assumption that how things are ordered in the data set we have is the column number (i.e. the first category of an air_date == Category 1).
